### ISSUE TITLE
jetway door 0

### ISSUE THREAD

**Issue by mherweg** [FGMEMBERS/VIP#1]
I suggest these values:

```
<aircraft>
<jetway-pos>
<x-tra>0.5</x-tra>
<y-rot>3.5</y-rot>
<z-rot>18</z-rot>
<hood-rot>15</hood-rot>
</jetway-pos>
</aircraft>
```

**Comment by FGDATA** [comment]
@mherweg 
Are these values for the 747 or the Lineage?
Surely they ought to be different
@IAHM-COL

**Comment by FGDATA** [comment]
https://github.com/FGMEMBERS/VIP/commit/d8fc6322352df7f0b84ba7a86102c1e9a551e6aa
