### ISSUE TITLE
Aircraft will not show up

### ISSUE THREAD

**Issue by CA1012** [FGMEMBERS/VIP#2]
I tried launching the 747 VVIP and I could spawn in, but the aircraft's 3d model was either in the bathroom or at a starbucks because i could not see it. please contact me so i can explain better. if you happen to have a screen sharing/viewing software installed i.e team viewer i could show you exactly what i see.

-Falcon

**Comment by FGDATA** [comment]
yup. This we know. Thanks for the report.

@JWocky

**Comment by legoboyvdlp** [comment]
In the bathroom.... or starbucks....
You make me laugh!

**Comment by FGDATA** [comment]
@CA1012 
The aircraft has come back from dinner on a very fancy restaurant

https://github.com/FGMEMBERS/VIP/commit/256b9882f33b670744646b2337e25b80a0698a38

I recommend you update (pull or redownload) and try again

Thanks again for the note
IH-COL

**Comment by FGDATA** [comment]
13:00 PST maybe too late for me to join today the pacific rim tour, but If I can get around my pc at that time, I'm bringing this 748VIP version in the Siegerflieger Livery

IH-COL
